### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by RealRedDragon** [yaldabaoth444/Asphalt9w#1]
Sorry but the alpha version is not workin on Windows 10. Or need more instructions to use it.

**Comment by yaldabaoth444** [comment]
example of how it works 
https://drive.google.com/file/d/1Qu-CvjC90X4gVDc5uLCnSMX07z1rw2Gu/view?usp=sharing

You need to replace all the pictures with your own or re-create the algorithm for your needs
..or what you mean by "doesn't work"

**Comment by yaldabaoth444** [comment]
the size of the game window matters, it must not change, otherwise the patterns will not be recognized on the screen

**Comment by RealRedDragon** [comment]
Я сделал всё, как на видео. Скрины кнопок заменил на свои и т.д. Не летит ракета. 
![Uploading 16168324384053995600362354000581.jpg…]()

**Comment by yaldabaoth444** [comment]
Привет, сможешь заархивировать всю папку и дать ссылку на скачивание? 
У меня сейчас другая версия, но в ней нужно дополнительно драйвера ставить https://tetherscript.s3-us-west-2.amazonaws.com/HVDK/HVDK+Standard_2.1_Installer.exe иначе движения мыши блокируются через какое-то время

**Comment by yaldabaoth444** [comment]
А еще хотел уточнить как у тебя окно Asphalt 9 называется? Он ищет окно с названием  "Asphalt 9: Legends"

**Comment by yaldabaoth444** [comment]
Обновил. Добавил возможность менять название окна с которого скриншот берется. Вангую в этом проблема была :)

**Comment by RealRedDragon** [comment]
Спасибо! Новую версию скачал, запускается без ошибок. Нужно время, чтобы сделать адаптированные скриншоты. Твои слишком большие, прога их из-за этого не видит, как я полагаю. На выходных постараюсь протестить.

**Comment by yaldabaoth444** [comment]
у меня 4к монитор просто, я сделал размер окна комфортный для себя..поэтому такие большие. А чем меньше размер окна, тем быстрее будет работать. Чем больше шаблонов в одной папке, тем медленнее. На моём Ryzen 5 3600 2-4 кадра в секунду, и в принципе этого хватает.

**Comment by yaldabaoth444** [comment]
Я как то нечаянно размер окна своего поменял, пришлось в точь в точь выставлять обратно. некотрые шаблоны перестали находиться
Добавил новый тег AREA_X..Y..W..H.. чтобы можно было указывать произвольную область экрана, на данный момент использую в области появления повортов/трамплинов
Можно свои алгоритмы работы придумывать. Возможно в будущем придётся еще свайп добавить, но пока без него обхожусь.

**Comment by AyazHere** [comment]
this is difficult, how a immature or the player who don't have any idea about pattern recognition, how can he manage to run it on our pc

**Comment by yaldabaoth444** [comment]
Sorry, You need to be able to make a screenshot of the game window and cut out the necessary images of buttons or play normally. This is an automation tool, not a plug and play
